--------------------------------------------------------------------------------
-- Copyright (c) 1995-2013 Xilinx, Inc.  All rights reserved.
--------------------------------------------------------------------------------
--   ____  ____
--  /   /\/   /
-- /___/  \  /    Vendor: Xilinx
-- \   \   \/     Version: P.20131013
--  \   \         Application: netgen
--  /   /         Filename: .vhd
-- /___/   /\     Timestamp: Sun Oct 25 15:48:41 2020
-- \   \  /  \ 
--  \___\/\___\
--             
-- Command	: -intstyle ise -ar Structure -tm MIPS_PROCESSOR -w -dir netgen/synthesis -ofmt vhdl -sim MIPS_PROCESSOR.ngc MIPS_PROCESSOR_synthesis.vhd 
-- Device	: xc6slx16-3-csg324
-- Input file	: MIPS_PROCESSOR.ngc
-- Output file	: \\vboxsvr\te2031\lab-repo\P8\netgen\synthesis\MIPS_PROCESSOR_synthesis.vhd
-- # of Entities	: 1
-- Design Name	: MIPS_PROCESSOR
-- Xilinx	: C:\Xilinx\14.7\ISE_DS\ISE\
--             
-- Purpose:    
--     This VHDL netlist is a verification model and uses simulation 
--     primitives which may not represent the true implementation of the 
--     device, however the netlist is functionally correct and should not 
--     be modified. This file cannot be synthesized and should only be used 
--     with supported simulation tools.
--             
-- Reference:  
--     Command Line Tools User Guide, Chapter 23
--     Synthesis and Simulation Design Guide, Chapter 6
--             
--------------------------------------------------------------------------------

