-intstyle "ise" -incremental -lib "secureip" -o "E:/Practica4/REG_FILE_REGISTERS_TESTBENCH_isim_beh.exe" -prj "E:/Practica4/REG_FILE_REGISTERS_TESTBENCH_beh.prj" "work.REG_FILE_REGISTERS_TESTBENCH" 
